-- 아이디, 비밀번호, 이름, 이메일, 가입일
CREATE TABLE KH_MEMBER(
	MEMBER_ID VARCHAR2(10) PRIMARY KEY,
	MEMBER_PW VARCHAR2(20) NOT NULL,
	MEMBER_NAME VARCHAR2(15) NOT NULL,
	EMAIL VARCHAR2(50),
	ENROLL_DATE DATE DEFAULT SYSDATE
);

INSERT INTO KH_MEMBER VALUES
('admin', 1234, '짱구', 'kh01@kh.com', DEFAULT);

INSERT INTO KH_MEMBER VALUES
('user01', 1234, '맹구', 'kh02@kh.com', DEFAULT);

INSERT INTO KH_MEMBER VALUES
('user02', 1234, '유리', 'kh03@kh.com', DEFAULT);

SELECT * FROM KH_MEMBER;

SELECT MEMBER_ID
FROM KH_MEMBER
WHERE MEMBER_ID = 'admin';

--20250317
--게시글 번호,
--게시글 카테고리,
--작성자,
--제목,
--내용,
--조회수,
--작성일
CREATE SEQUENCE SEQ_KH_BOARD;
CREATE TABLE KH_BOARD(
	BOARD_NO NUMBER PRIMARY KEY,
	BOARD_CATEGORY VARCHAR2(20) NOT NULL,
	BOARD_WRITER VARCHAR2(20) REFERENCES KH_MEMBER,
	BOARD_TITLE VARCHAR2(300) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	COUNT NUMBER DEFAULT 0,
	CREATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM KH_BOARD;

ALTER TABLE KH_MEMBER MODIFY MEMBER_PW VARCHAR2(60);

UPDATE KH_MEMBER
SET    MEMBER_PW = '$2a$10$OaHH1LzKKMXOLwQTBRL0Me3Ux3bLgJ0zLJtdq2J1HOuGWBAS/sHJW';

SELECT * FROM KH_MEMBER;
COMMIT;


-- 게시글용 테이블 구현하기
-- 파일 첨부 기능 구현할 것 + 댓글 기능 구현할 것

CREATE TABLE TB_SPRING_BOARD(
	BOARD_NO NUMBER GENEREATED ALWAYS AS IDENTITY PRIMARY KEY,
	BOARD_TITLE VARCHAR2(200) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER VARCHAR2(10) NOT NULL REFERENCES KH_MEMBER,
	COUNT NUMBER DEFAULT 0 NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	CHANGE_NAME VARCHAR2(200),
	STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);

DROP TABLE TB_SPRING_BOARD;
INSERT INTO TB_SPRING_BOARD(BOARD_TITLE, BOARD_WRITER)
VALUES('두 번째 글', 'admin');
SELECT * FROM TB_SPRING_BOARD;


-- PK
-- 작성자
-- 내용
-- 작성일	
-- 어떤 게시글에 달려있는가
CREATE TABLE TB_REPLY(
	REPLY_NO NUMBER PRIMARY KEY,
	REPLY_WRITER VARCHAR(10) NOT NULL REFERENCES KH_MEMBER,
	REPLY_CONTENT VARCHAR2(500) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	REF_BOARD_NO NUMBER NOT NULL REFERENCES TB_SPRING_BOARD
);

INSERT INTO TB_REPLY
VALUES(SEQ_RNO.NEXTVAL, 'user01', '호호호', SYSDATE, 1);

INSERT INTO TB_REPLY
VALUES(SEQ_RNO.NEXTVAL, 'user02', '하하하', SYSDATE, 1);

INSERT INTO TB_REPLY
VALUES(SEQ_RNO.NEXTVAL, 'admin', '히히히', SYSDATE, 1);

INSERT INTO TB_REPLY
VALUES(SEQ_RNO.NEXTVAL, 'user01', '후후후', SYSDATE, 1);

COMMIT;

CREATE SEQUENCE SEQ_RNO;
SELECT * FROM TB_REPLY;

SELECT 
	  BOARD_NO boardNo
	, BOARD_TITLE boardTitle
	, BOARD_CONTENT boardContent
	, BOARD_WRITER boardWriter
	, TB_SPRING_BOARD.CREATE_DATE createDate
	, CHANGE_NAME changeName
	, REPLY_NO replyNo
	, REPLY_WRITER replyWriter
	, REPLY_CONTENT replyContent
	, REF_BOARD_NO refBoardNo
	, TB_REPLY.CREATE_DATE createDate
 FROM
 	  TB_SPRING_BOARD
 LEFT
 JOIN
 	  TB_REPLY ON (BOARD_NO = REF_BOARD_NO)
WHERE 
	  BOARD_NO = 1;

-----
 	  
	













