CREATE TABLE JAR_MEMBER(
	MEMBER_ID VARCHAR2(10) PRIMARY KEY,
	MEMBER_PW VARCHAR2(20) NOT NULL,
	MEMBER_NAME VARCHAR2(15) NOT NULL,
	EMAIL VARCHAR2(50),
	ENROLL_DATE DATE DEFAULT SYSDATE
);

INSERT INTO JAR_MEMBER VALUES
('admin', 1234, '짱구', 'JAR01@jar.com', DEFAULT);

INSERT INTO JAR_MEMBER VALUES
('user01', 1234, '맹구', 'JAR02@jar.com', DEFAULT);

INSERT INTO JAR_MEMBER VALUES
('user02', 1234, '유리', 'JAR03@jar.com', DEFAULT);

SELECT * FROM JAR_MEMBER;

SELECT MEMBER_ID
FROM JAR_MEMBER
WHERE MEMBER_ID = 'admin';