-- 아이디, 비밀번호, 이름, 이메일, 가입일
CREATE TABLE KH_MEMBER(
	MEMBER_ID VARCHAR2(10) PRIMARY KEY,
	MEMBER_PW VARCHAR2(20) NOT NULL,
	MEMBER_NAME VARCHAR2(15) NOT NULL,
	EMAIL VARCHAR2(50),
	ENROLL_DATE DATE DEFAULT SYSDATE
);

INSERT INTO KH_MEMBER VALUES
('admin', 1234, '짱구', 'kh01@kh.com', DEFAULT);

INSERT INTO KH_MEMBER VALUES
('user01', 1234, '맹구', 'kh02@kh.com', DEFAULT);

INSERT INTO KH_MEMBER VALUES
('user02', 1234, '유리', 'kh03@kh.com', DEFAULT);

SELECT * FROM KH_MEMBER;

SELECT MEMBER_ID
FROM KH_MEMBER
WHERE MEMBER_ID = 'admin';